photo_objects/django/urls.py
from django.contrib.auth import views as auth_views
from django.http import HttpResponseRedirect
from django.urls import path

from .views import api, ui

app_name = "photo_objects"
urlpatterns = [
    path("_auth", api.has_permission),
    path("api/albums", api.albums),
    path("api/albums/<str:album_key>", api.album),
    path(
        "api/albums/<str:album_key>/photos",
        api.photos,
        name="api_photos",
    ),
    path("api/albums/<str:album_key>/photos/<str:photo_key>", api.photo),
    path(
        "api/albums/<str:album_key>/photos/<str:photo_key>/change-requests",
        api.photo_change_requests,
    ),
    path(
        "api/photo-change-requests/expected",
        api.expected_photo_change_requests,
    ),
    path("api/albums/<str:album_key>/photos/<str:photo_key>/img", api.get_img),
    # TODO: ui views
    path('', lambda _: HttpResponseRedirect('albums')),
    path(
        "albums",
        ui.list_albums,
        name="list_albums",
    ),
    path(
        "albums/_new",
        ui.new_album,
        name="new_album",
    ),
    path(
        "albums/<str:album_key>",
        ui.show_album,
        name="show_album",
    ),
    path(
        "albums/<str:album_key>/_edit",
        ui.edit_album,
        name="edit_album",
    ),
    path(
        "albums/<str:album_key>/_delete",
        ui.delete_album,
        name="delete_album",
    ),
    path(
        "albums/<str:album_key>/photos/_upload",
        ui.upload_photos,
        name="upload_photos",
    ),
    path(
        "albums/<str:album_key>/photos/<str:photo_key>",
        ui.show_photo,
        name="show_photo",
    ),
    path(
        "albums/<str:album_key>/photos/<str:photo_key>/_edit",
        ui.edit_photo,
        name="edit_photo",
    ),
    path(
        "albums/<str:album_key>/photos/<str:photo_key>/_delete",
        ui.delete_photo,
        name="delete_photo",
    ),
    path(
        "photo-change-requests/_next",
        ui.next_photo_change_request,
        name="next_photo_change_request",
    ),
    path(
        "photo-change-requests/<int:cr_id>/_review",
        ui.review_photo_change_request,
        name="review_photo_change_request",
    ),
    path(
        "configuration",
        ui.configuration,
        name="configuration",
    ),
    # TODO: img/<str:album_key>/<str:photo_key>/<str:size_key> path
    path(
        "users/login",
        ui.login,
        name="login",
    ),
    path(
        "users/logout",
        auth_views.LogoutView.as_view(),
        name="logout",
    ),
]

photo_objects/django/models.py
from typing import Self

from django.db import models
from django.db.models.query import QuerySet
from django.db.models.signals import pre_delete, pre_save
from django.contrib.sites.models import Site
from django.core.validators import RegexValidator
from django.utils.translation import gettext_lazy as _

from photo_objects.utils import first_paragraph_textcontent, timestamp_str


album_key_validator = RegexValidator(
    r"^[a-zA-Z0-9._-]+$",
    "Album key must only contain alphanumeric characters, dots, underscores "
    "and hyphens.")
photo_key_validator = RegexValidator(
    r"^[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+$",
    "Photo key must contain album key and filename. These must be separated "
    "with slash. Both parts must only contain alphanumeric characters, dots, "
    "underscores and hyphens.")


def _str(key, **kwargs):
    details = ', '.join(f'{k}={v}' for k, v in kwargs.items() if k and v)
    return f'{key} ({details})' if details else key


class BaseModel(models.Model):
    title = models.CharField(blank=True)
    description = models.TextField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def to_json(self):
        return dict(
            title=self.title,
            description=self.description,
            created_at=timestamp_str(self.created_at),
            updated_at=timestamp_str(self.updated_at),
        )


class Album(BaseModel):
    class Meta:
        ordering = ["-first_timestamp", "-last_timestamp", "key"]

    class Visibility(models.TextChoices):
        PUBLIC = "public", _("Public")
        HIDDEN = "hidden", _("Hidden")
        PRIVATE = "private", _("Private")
        ADMIN = "", _("Admin")

    key = models.CharField(primary_key=True, validators=[album_key_validator])
    visibility = models.CharField(
        blank=True,
        db_default=Visibility.PRIVATE,
        default=Visibility.PRIVATE,
        choices=Visibility)

    cover_photo = models.ForeignKey(
        "Photo",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="+")
    first_timestamp = models.DateTimeField(blank=True, null=True)
    last_timestamp = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return _str(self.key, title=self.title, visibility=self.visibility)

    def to_json(self):
        return dict(
            **super().to_json(),
            key=self.key,
            visibility=self.visibility,
            cover_photo=(
                self.cover_photo.filename if self.cover_photo else None),
            first_timestamp=timestamp_str(self.first_timestamp),
            last_timestamp=timestamp_str(self.last_timestamp),
        )


class Photo(BaseModel):
    class Meta:
        ordering = ["timestamp"]

    key = models.CharField(primary_key=True, validators=[photo_key_validator])
    album = models.ForeignKey("Album", null=True, on_delete=models.PROTECT)

    timestamp = models.DateTimeField()

    height = models.PositiveIntegerField()
    width = models.PositiveIntegerField()
    tiny_base64 = models.TextField(blank=True)

    camera_make = models.CharField(blank=True)
    camera_model = models.CharField(blank=True)
    lens_make = models.CharField(blank=True)
    lens_model = models.CharField(blank=True)

    focal_length = models.FloatField(blank=True, null=True)
    f_number = models.FloatField(blank=True, null=True)
    exposure_time = models.FloatField(blank=True, null=True)
    iso_speed = models.IntegerField(blank=True, null=True)

    alt_text = models.TextField(blank=True)

    def __str__(self):
        return _str(
            self.key,
            title=self.title,
            timestamp=self.timestamp.isoformat()
        )

    @property
    def alt(self):
        if self.alt_text:
            return self.alt_text

        if self.description:
            text = first_paragraph_textcontent(self.description)
            if text:
                return text

        return self.title or self.filename

    @property
    def filename(self):
        return self.key.split('/')[-1]

    @property
    def thumbnail_height(self):
        return 256

    @property
    def thumbnail_width(self):
        return round(self.width / self.height * self.thumbnail_height)

    def previous(self, photo_set: QuerySet[Self]) -> Self:
        qs = photo_set.order_by('timestamp')

        return qs.filter(timestamp__lt=self.timestamp).last() or qs.last()

    def next(self, photo_set: QuerySet[Self]) -> Self:
        qs = photo_set.order_by('timestamp')

        return qs.filter(timestamp__gt=self.timestamp).first() or qs.first()

    def to_json(self):
        album_key = self.album.key if self.album else None

        return dict(
            **super().to_json(),
            key=self.key,
            filename=self.filename,
            album=album_key,
            timestamp=self.timestamp.isoformat(),
            height=self.height,
            width=self.width,
            tiny_base64=self.tiny_base64,
            camera_make=self.camera_make,
            camera_model=self.camera_model,
            lens_make=self.lens_make,
            lens_model=self.lens_model,
            focal_length=self.focal_length,
            f_number=self.f_number,
            exposure_time=self.exposure_time,
            iso_speed=self.iso_speed,
            alt_text=self.alt_text,
        )


class PhotoChangeRequest(models.Model):
    class Meta:
        ordering = ["-created_at"]

    created_at = models.DateTimeField(auto_now_add=True)

    photo = models.ForeignKey(
        "Photo",
        on_delete=models.CASCADE,
        related_name="change_requests")

    alt_text = models.TextField()

    def __str__(self):
        return _str(
            self.photo.key,
            created_at=self.created_at.isoformat()
        )

    def to_json(self):
        return dict(
            id=self.id,
            photo=self.photo.key,
            created_at=timestamp_str(self.created_at),
            alt_text=self.alt_text,
        )


SETTINGS_CACHE = {}


class SiteSettingsManager(models.Manager):
    def get(self, site: Site):
        cached = SETTINGS_CACHE.get(site.id)
        if cached:
            return cached
        settings, _ = self.get_or_create(site=site)
        SETTINGS_CACHE[site.id] = settings
        return settings


class SiteSettings(models.Model):
    class Meta:
        verbose_name_plural = "site settings"

    site = models.OneToOneField(
        Site, on_delete=models.CASCADE, related_name="settings")

    description = models.TextField(
        blank=True,
        help_text=_(
            "Description of the site, used in site level meta description "
            "tags and social media previews."),
    )
    preview_image = models.ForeignKey(
        Photo,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        help_text=_(
            "Photo to use as the site level social media preview image."),
    )
    copyright_notice = models.CharField(
        blank=True,
        help_text=_(
            "Copyright notice to display in the site footer. Content will be "
            "HTML-escaped before rendering."),
    )
    objects = SiteSettingsManager()

    def __str__(self):
        return f"Settings for {self.site.name}"


def clear_cached_settings(sender, **kwargs):
    site_id = kwargs.get("instance").site.id
    if site_id in SETTINGS_CACHE:
        del SETTINGS_CACHE[site_id]


pre_save.connect(clear_cached_settings, sender=SiteSettings)
pre_delete.connect(clear_cached_settings, sender=SiteSettings)


class Backup(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(blank=True)
    status = models.TextField(blank=True)

    def __str__(self):
        return _str(
            f'Backup {self.id}',
            created_at=self.created_at,
            status=self.status,
            comment=self.comment,
        )

    def to_json(self):
        return dict(
            id=self.id,
            created_at=timestamp_str(self.created_at),
            comment=self.comment,
        )

photo_objects/django/templates/photo_objects/photo/show.html
{% extends 'photo_objects/base.html' %}

{% block header %}
{% include 'photo_objects/header.html' %}
{% endblock %}

{% block content %}
<div class="photo-and-details">
  <div class="photo surface">
    <img src="/img/{{ photo.album.key }}/{{ photo.filename }}/lg" alt="{{ photo.alt }}"
      style="background: url(data:image/png;base64,{{ photo.tiny_base64 }}); background-size: 100% 100%; font-size: 0;"
      height="{{ photo.height }}" width="{{ photo.width }}" />
  </div>
  {% include 'photo_objects/details.html' %}
</div>

<div class="actions">
  <a id="previous" class="action" href="{% url 'photo_objects:show_photo' photo.album.key previous_filename %}">←</a>
  <a id="next" class="action" href="{% url 'photo_objects:show_photo' photo.album.key next_filename %}">→</a>
  {% if perms.photo_objects.change_photo %}
  <a class="action" href="{% url 'photo_objects:edit_photo' photo.album.key photo.filename %}">Edit photo</a>
  {% endif %}
  {% if perms.photo_objects.delete_photo %}
  <a class="action delete" href="{% url 'photo_objects:delete_photo' photo.album.key photo.filename %}">Delete photo</a>
  {% endif %}
</div>
<script>
  document.addEventListener('keydown', function (event) {
    if (event.key === 'ArrowLeft') {
      document.querySelector('a#previous').click();
    } else if (event.key === 'ArrowRight') {
      document.querySelector('a#next').click();
    }
  });

  window.addEventListener('pageshow', function (event) {
    // Reset page position to the top.
    window.scrollTo(0, 0);

    const photo = document.querySelector('.photo img');
    if (!photo) {
      return;
    }

    // Firefox remembers photo position when navigating back to photo with browesrs back button.
    photo.style.left = 0;
    photo.style.opacity = 1;
  });

  // Wait for load event instead of DOMContentLoaded so that images and styles have been loaded before configuring the event listeners.
  addEventListener("load", function () {
    const photo = document.querySelector('.photo img');
    const surface = document.querySelector('.photo.surface');

    if (!photo || !surface) {
      return
    }

    const trigger = photo.offsetWidth * 0.4;

    var startX;
    var deltaX;


    photo.addEventListener('touchstart', function (event) {
      startX = event.changedTouches[0].pageX;
      photo.classList.add('touch');
    });

    photo.addEventListener('touchmove', function (event) {
      deltaX = event.changedTouches[0].pageX - startX;

      photo.style.left = deltaX + 'px';
      photo.style.opacity = 1 - Math.abs(deltaX) / trigger * 0.4;

      if (deltaX > trigger) {
        surface.classList.add("previous");
      } else if (deltaX < -trigger) {
        surface.classList.add("next");
      } else {
        surface.classList.remove("previous", "next");
      }
    });

    photo.addEventListener('touchend', function (event) {
      if (deltaX > trigger) {
        document.querySelector('a#previous').click();
      } else if (deltaX < -trigger) {
        document.querySelector('a#next').click();
      } else {
        photo.style.left = 0;
        photo.style.opacity = 1;
      }

      photo.classList.remove('touch');
    });
  });
</script>
{% endblock %}

photo_objects/django/templates/photo_objects/photo/upload.html
{% extends 'photo_objects/base.html' %}

{% block header %}
{% include 'photo_objects/header.html' %}
{% endblock %}

{% block content %}
<!-- TODO: Instructions? -->

{% if preview %}
{% include 'photo_objects/preview.html' %}
{% endif %}
<div class="form">
  <form action="">
    {% csrf_token %}
    {% if info %}
    <div class="info-banner">{{ info }}</div>
    {% endif %}
    <ul>
      <li>
        <ul class="errorlist" id="id_photos_error"></ul>
        <label for="id_photos" tabindex="0" class="empty">Drag and drop photos here or click to open upload dialog.</label>
        <input type="file" name="photos" multiple="" required="" id="id_photos" aria-describedby="id_photos_help" />
        <span id="id_photos_help" class="helptext">Photo upload will start immediately after dropping or selecting the
          files. You can see the upload status in the area above.</span>
      </li>
    </ul>
    <a class="action" href="{% url 'photo_objects:show_album' album.key %}">Done</a>
  </form>
</div>
<script>
  const url = "{% url 'photo_objects:api_photos' album.key %}";
  const csrfToken = document.querySelector('input[name=csrfmiddlewaretoken]').value;

  function addError(filename, message, wrapper, status) {
    wrapper.classList.remove('uploading');
    wrapper.classList.add('failed');
    status.textContent = 'Failed';

    const errorList = document.querySelector('#id_photos_error');
    const li = document.createElement('li');
    li.textContent = `Failed to upload ${filename}: ${message}`;
    errorList.appendChild(li);
  }

  function uploadPhoto(file, wrapper, status) {
    const data = new FormData()
    data.append('file', file)

    fetch(url, {
      method: 'POST',
      headers: {
        'X-CSRFToken': csrfToken,
      },
      body: data,
    }).then(response => {
      if (response.ok) {
        wrapper.classList.remove('uploading');
        wrapper.classList.add('ok');
        status.textContent = 'Ready';
      } else {
        return response.json();
      }
    }).then(data => {
      if (data) {
        try {
          addError(file.name, data.errors.key[0].message, wrapper, status);
        } catch (_) {
          addError(file.name, data.title, wrapper, status);
        }
      }
    }).catch(err => {
      addError(file.name, err, wrapper, status);
    });
  }

  function uploadPhotos() {
    const input = document.querySelector('#id_photos');
    if (input.files.length > 0) {
      const label = document.querySelector('label[for=id_photos]');
      if (label.classList.contains('empty')) {
        label.textContent = '';
        label.classList.remove('empty');
      }

      for (let i = 0; i < input.files.length; i++) {
        const file = input.files[i];

        const wrapper = document.createElement('div');
        wrapper.classList.add('photo-upload');
        wrapper.classList.add('uploading');

        const status = document.createElement('div');
        status.classList.add('status');
        status.textContent = 'Uploading';

        const img = document.createElement('img');
        img.alt = file.name;
        img.src = URL.createObjectURL(file);

        wrapper.appendChild(img);
        wrapper.appendChild(status);
        label.appendChild(wrapper);

        uploadPhoto(file, wrapper, status);
      }
    }
  }

  // Render images instead of label after selecting files
  document.querySelector('#id_photos').addEventListener('change', uploadPhotos);

  // Make the label focusable as the input is hidden
  document.querySelector('label[for=id_photos]').setAttribute('tabindex', '0');

  // Handle enter and space key events on label
  document.querySelector('label[for=id_photos]').addEventListener('keydown', function (event) {
    if (event.code === 'Enter' || event.code === 'Space') {
      event.preventDefault();
      document.querySelector('#id_photos').click();
    }
  });

  // Allow drop events on label
  document.querySelector('label[for=id_photos]').addEventListener('dragover', function (event) {
    event.preventDefault();
  });

  // Handle drop event on label
  document.querySelector('label[for=id_photos]').addEventListener('drop', function (event) {
    event.preventDefault();

    const input = document.querySelector('#id_photos');
    input.files = event.dataTransfer.files;
    uploadPhotos();
  });
</script>
{% endblock %}