photo_objects/django/urls.py
from django.contrib.auth import views as auth_views
from django.http import HttpResponseRedirect
from django.urls import path

from .views import api, ui

app_name = "photo_objects"
urlpatterns = [
    path("_auth", api.has_permission),
    path("api/albums", api.albums),
    path("api/albums/<str:album_key>", api.album),
    path(
        "api/albums/<str:album_key>/photos",
        api.photos,
        name="api_photos",
    ),
    path("api/albums/<str:album_key>/photos/<str:photo_key>", api.photo),
    path(
        "api/albums/<str:album_key>/photos/<str:photo_key>/change-requests",
        api.photo_change_requests,
    ),
    path(
        "api/photo-change-requests/expected",
        api.expected_photo_change_requests,
    ),
    path("api/albums/<str:album_key>/photos/<str:photo_key>/img", api.get_img),
    # TODO: ui views
    path('', lambda _: HttpResponseRedirect('albums')),
    path(
        "albums",
        ui.list_albums,
        name="list_albums",
    ),
    path(
        "albums/_new",
        ui.new_album,
        name="new_album",
    ),
    path(
        "albums/<str:album_key>",
        ui.show_album,
        name="show_album",
    ),
    path(
        "albums/<str:album_key>/_edit",
        ui.edit_album,
        name="edit_album",
    ),
    path(
        "albums/<str:album_key>/_delete",
        ui.delete_album,
        name="delete_album",
    ),
    path(
        "albums/<str:album_key>/photos/_upload",
        ui.upload_photos,
        name="upload_photos",
    ),
    path(
        "albums/<str:album_key>/photos/<str:photo_key>",
        ui.show_photo,
        name="show_photo",
    ),
    path(
        "albums/<str:album_key>/photos/<str:photo_key>/_edit",
        ui.edit_photo,
        name="edit_photo",
    ),
    path(
        "albums/<str:album_key>/photos/<str:photo_key>/_delete",
        ui.delete_photo,
        name="delete_photo",
    ),
    path(
        "photo-change-requests/_next",
        ui.next_photo_change_request,
        name="next_photo_change_request",
    ),
    path(
        "photo-change-requests/<int:cr_id>/_review",
        ui.review_photo_change_request,
        name="review_photo_change_request",
    ),
    path(
        "configuration",
        ui.configuration,
        name="configuration",
    ),
    # TODO: img/<str:album_key>/<str:photo_key>/<str:size_key> path
    path(
        "users/login",
        ui.login,
        name="login",
    ),
    path(
        "users/logout",
        auth_views.LogoutView.as_view(),
        name="logout",
    ),
]

photo_objects/django/models.py
from typing import Self

from django.db import models
from django.db.models.query import QuerySet
from django.db.models.signals import pre_delete, pre_save
from django.contrib.sites.models import Site
from django.core.validators import RegexValidator
from django.utils.translation import gettext_lazy as _

from photo_objects.utils import first_paragraph_textcontent, timestamp_str


album_key_validator = RegexValidator(
    r"^[a-zA-Z0-9._-]+$",
    "Album key must only contain alphanumeric characters, dots, underscores "
    "and hyphens.")
photo_key_validator = RegexValidator(
    r"^[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+$",
    "Photo key must contain album key and filename. These must be separated "
    "with slash. Both parts must only contain alphanumeric characters, dots, "
    "underscores and hyphens.")


def _str(key, **kwargs):
    details = ', '.join(f'{k}={v}' for k, v in kwargs.items() if k and v)
    return f'{key} ({details})' if details else key


class BaseModel(models.Model):
    title = models.CharField(blank=True)
    description = models.TextField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def to_json(self):
        return dict(
            title=self.title,
            description=self.description,
            created_at=timestamp_str(self.created_at),
            updated_at=timestamp_str(self.updated_at),
        )


class Album(BaseModel):
    class Meta:
        ordering = ["-first_timestamp", "-last_timestamp", "key"]

    class Visibility(models.TextChoices):
        PUBLIC = "public", _("Public")
        HIDDEN = "hidden", _("Hidden")
        PRIVATE = "private", _("Private")
        ADMIN = "", _("Admin")

    key = models.CharField(primary_key=True, validators=[album_key_validator])
    visibility = models.CharField(
        blank=True,
        db_default=Visibility.PRIVATE,
        default=Visibility.PRIVATE,
        choices=Visibility)

    cover_photo = models.ForeignKey(
        "Photo",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="+")
    first_timestamp = models.DateTimeField(blank=True, null=True)
    last_timestamp = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return _str(self.key, title=self.title, visibility=self.visibility)

    def to_json(self):
        return dict(
            **super().to_json(),
            key=self.key,
            visibility=self.visibility,
            cover_photo=(
                self.cover_photo.filename if self.cover_photo else None),
            first_timestamp=timestamp_str(self.first_timestamp),
            last_timestamp=timestamp_str(self.last_timestamp),
        )


class Photo(BaseModel):
    class Meta:
        ordering = ["timestamp"]

    key = models.CharField(primary_key=True, validators=[photo_key_validator])
    album = models.ForeignKey("Album", null=True, on_delete=models.PROTECT)

    timestamp = models.DateTimeField()

    height = models.PositiveIntegerField()
    width = models.PositiveIntegerField()
    tiny_base64 = models.TextField(blank=True)

    camera_make = models.CharField(blank=True)
    camera_model = models.CharField(blank=True)
    lens_make = models.CharField(blank=True)
    lens_model = models.CharField(blank=True)

    focal_length = models.FloatField(blank=True, null=True)
    f_number = models.FloatField(blank=True, null=True)
    exposure_time = models.FloatField(blank=True, null=True)
    iso_speed = models.IntegerField(blank=True, null=True)

    alt_text = models.TextField(blank=True)

    def __str__(self):
        return _str(
            self.key,
            title=self.title,
            timestamp=self.timestamp.isoformat()
        )

    @property
    def alt(self):
        if self.alt_text:
            return self.alt_text

        if self.description:
            text = first_paragraph_textcontent(self.description)
            if text:
                return text

        return self.title or self.filename

    @property
    def filename(self):
        return self.key.split('/')[-1]

    @property
    def thumbnail_height(self):
        return 256

    @property
    def thumbnail_width(self):
        return round(self.width / self.height * self.thumbnail_height)

    def previous(self, photo_set: QuerySet[Self]) -> Self:
        qs = photo_set.order_by('timestamp')

        return qs.filter(timestamp__lt=self.timestamp).last() or qs.last()

    def next(self, photo_set: QuerySet[Self]) -> Self:
        qs = photo_set.order_by('timestamp')

        return qs.filter(timestamp__gt=self.timestamp).first() or qs.first()

    def to_json(self):
        album_key = self.album.key if self.album else None

        return dict(
            **super().to_json(),
            key=self.key,
            filename=self.filename,
            album=album_key,
            timestamp=self.timestamp.isoformat(),
            height=self.height,
            width=self.width,
            tiny_base64=self.tiny_base64,
            camera_make=self.camera_make,
            camera_model=self.camera_model,
            lens_make=self.lens_make,
            lens_model=self.lens_model,
            focal_length=self.focal_length,
            f_number=self.f_number,
            exposure_time=self.exposure_time,
            iso_speed=self.iso_speed,
            alt_text=self.alt_text,
        )


class PhotoChangeRequest(models.Model):
    class Meta:
        ordering = ["-created_at"]

    created_at = models.DateTimeField(auto_now_add=True)

    photo = models.ForeignKey(
        "Photo",
        on_delete=models.CASCADE,
        related_name="change_requests")

    alt_text = models.TextField()

    def __str__(self):
        return _str(
            self.photo.key,
            created_at=self.created_at.isoformat()
        )

    def to_json(self):
        return dict(
            id=self.id,
            photo=self.photo.key,
            created_at=timestamp_str(self.created_at),
            alt_text=self.alt_text,
        )


SETTINGS_CACHE = {}


class SiteSettingsManager(models.Manager):
    def get(self, site: Site):
        cached = SETTINGS_CACHE.get(site.id)
        if cached:
            return cached
        settings, _ = self.get_or_create(site=site)
        SETTINGS_CACHE[site.id] = settings
        return settings


class SiteSettings(models.Model):
    class Meta:
        verbose_name_plural = "site settings"

    site = models.OneToOneField(
        Site, on_delete=models.CASCADE, related_name="settings")

    description = models.TextField(
        blank=True,
        help_text=_(
            "Description of the site, used in site level meta description "
            "tags and social media previews."),
    )
    preview_image = models.ForeignKey(
        Photo,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        help_text=_(
            "Photo to use as the site level social media preview image."),
    )
    copyright_notice = models.CharField(
        blank=True,
        help_text=_(
            "Copyright notice to display in the site footer. Content will be "
            "HTML-escaped before rendering."),
    )
    objects = SiteSettingsManager()

    def __str__(self):
        return f"Settings for {self.site.name}"


def clear_cached_settings(sender, **kwargs):
    site_id = kwargs.get("instance").site.id
    if site_id in SETTINGS_CACHE:
        del SETTINGS_CACHE[site_id]


pre_save.connect(clear_cached_settings, sender=SiteSettings)
pre_delete.connect(clear_cached_settings, sender=SiteSettings)


class Backup(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(blank=True)
    status = models.TextField(blank=True)

    def __str__(self):
        return _str(
            f'Backup {self.id}',
            created_at=self.created_at,
            status=self.status,
            comment=self.comment,
        )

    def to_json(self):
        return dict(
            id=self.id,
            created_at=timestamp_str(self.created_at),
            comment=self.comment,
        )

photo_objects/django/templates/photo_objects/base.html
{% load photo_objects_extras %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>{% if title %}{{ title }} - {% endif %}{% if request.site and request.site.domain != "example.com" %}{{ request.site.name }}{% else %}Photo Objects{% endif %}</title>
  {% if description %}
  <meta name="description" content="{{ description }}" />
  {% endif %}
  <meta charset="utf-8" />
  <meta name="theme-color" content="#191b1f" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  {% meta_og %}

  {% load static %}
  <link rel="icon" href="{% static 'photo_objects/favicon.svg' %}" type="image/svg+xml">
  <link rel="preload" href="{% static 'photo_objects/SourceSans3.ttf' %}" as="font" type="font/ttf" crossorigin>
  <link rel="preload" href="{% static 'photo_objects/SourceCodePro.ttf' %}" as="font" type="font/ttf" crossorigin>
  <link rel="stylesheet" href="{% static 'photo_objects/global.css' %}">
</head>

<body>
  <header class="{{ width|default:'wide' }}">
    {% block header %}{% endblock %}
  </header>
  <main class="{{ width|default:'wide' }}">
    {% block content %}{% endblock %}
  </main>
  <footer class="{{ width|default:'wide' }}">
    <div class="photo-objects">
      <svg viewBox="0 0 32 32">
        <path
          d="M 29 31 C 30 31 31 30 31 29 L 31 3 C 31 2 30 1 29 1 L 3 1 C 2 1 1 2 1 3 L 1 29 C 1 30 2 31 3 31 L 29 31 M 12 28 C 9 28 10 28 7 12 C 6.8 11 7 11 8 11 L 16.5 11 L 20 4 A 1 1 0 1 1 22.5 5 L 19.5 11 L 24 11 C 25.2 11 25 11 25 12 C 21.5 28 22.5 28 19.5 28 L 12 28 M 14.75 15 A 1.25 1.25 0 0 0 17.25 15 A 1.25 1.25 0 0 0 14.75 15"
          fill="currentColor" />
      </svg>
      <span>
        <a href="https://github.com/kangasta/photo-objects" target="_blank">photo-objects</a>
        {% if photo_objects_metadata and photo_objects_metadata.version %}
        at v{{ photo_objects_metadata.version }}
        {% endif %}
      </span>
    </div>
    {% copyright_notice %}
    <!-- TODO: Links to Docs, GitHub, ... -->
  </footer>
</body>

</html>

photo_objects/django/templates/photo_objects/configuration.html
{% extends 'photo_objects/base.html' %}

{% block header %}
{% include 'photo_objects/header.html' %}
{% endblock %}

{% block content %}
{% if preview %}
{% include 'photo_objects/preview.html' %}
{% endif %}
<div class="configuration">
  <ul>
    {% for i in validations %}
    <li>
      <div>
        <span class="check">{{ i.check }}:</span>
        <span class="status {{ i.status|lower }}">{{ i.status }}</span>
      </div>
      {% if i.detail %}
      <div class="helptext">
        {{ i.detail }}
      </div>
      {% endif %}
    </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

photo_objects/django/templates/photo_objects/delete.html
{% extends 'photo_objects/base.html' %}

{% block header %}
{% include 'photo_objects/header.html' %}
{% endblock %}

{% block content %}

<!-- TODO: Instructions? -->

{% if preview %}
{% include 'photo_objects/preview.html' %}
{% endif %}
<div class="form">
  <form action="" method="post">
    <p>Are you sure you want to delete <span class="resource-highlight">{{ resource }}</span>? This action can not be undone.</p>
    {% csrf_token %}
    {% if error %}
    <p class="error">{{ error }}</p>
    {% else %}
    <button class="delete" type="submit">Delete</button>
    {% endif %}
  </form>
</div>
{% endblock %}

photo_objects/django/templates/photo_objects/details.html
{% load photo_objects_extras %}
<dl>
  {% for key, value in details.items %}
  {% if value %}
  <dt>{{ key }}</dt>
  {% if value|is_list %}
  <dd class="list">
    {% for i in value %}
    <div class="item">
      {{ i }}
    </div>
    {% endfor %}
  </dd>
  {% elif value|is_datetime %}
  <dd>
    <time datetime="{{ value|date:'c' }}">
      {{ value|date:"D, d M Y H:i" }}
      <span class="secondary">{{ value|date:"T" }}</span>
    </time>
  </dd>
  {% else %}
  <dd>{{ value }}</dd>
  {% endif %}
  {% endif %}
  {% endfor %}
</dl>

photo_objects/django/templates/photo_objects/form.html
{% extends 'photo_objects/base.html' %}

{% block header %}
{% include 'photo_objects/header.html' %}
{% endblock %}

{% block content %}
{% if info %}
<div class="info-banner">{{ info }}</div>
{% endif %}
{% if preview %}
{% include 'photo_objects/preview.html' %}
{% endif %}
<div class="form {{ class|default:'' }}">
  <form action="" method="post">
    {% if instructions %}
    <div class="instructions">
      {{ instructions }}
    </div>
    {% endif %}
    {% csrf_token %}
    <ul>
      {{ form.as_ul }}
    </ul>
    <button type="submit">{{ action|default:'Save'}}</button>
  </form>
</div>
{% endblock %}

photo_objects/django/templates/photo_objects/header.html
{% load photo_objects_extras %}
{% url 'photo_objects:login' as login_url %}
<div class="title-and-back-link">
  <div class="back-link">
    {% if back %}
    {% if not back.root %}
    <span>… / </span>
    {% endif %}<a href="{{ back.url }}">{{ back.text }}</a><span> /</span>
    {% else %}
    <span>{{ request.site.name }} /</span>
    {% endif %}
  </div>
  <h1>{{ title }}</h1>
</div>
{% if user.is_authenticated %}
<button aria-label="Open user menu" class="user-profile" onclick="openUserModal()"
  title="Logged in as {{ user|display_name }}">
  {% include 'photo_objects/user-profile-content.html' %}
</button>
{% elif request.path != login_url %}
<a href="{% url 'photo_objects:login' %}?next={{ request.path }}">Login</a>
{% endif %}

{% if user.is_authenticated %}
<dialog class="user-modal" onclick="handleClick(event)" onclose="handleClose()">
  <!-- Catch click events to easily detect if target is dialog or its backdrop. -->
  <div class="user-modal-content">
    <!-- Manual focus trap: move focus to last element in dialog. -->
    <div id="user-modal-pre" tabindex="0" onfocus="focusElement('#user-modal-logout')"></div>
    <div class="user-modal-header">
      <div class="user-details">
        <div class="user-profile">
          {% include 'photo_objects/user-profile-content.html' %}
        </div>
        <div class="labels">
          <div class="label-primary">{{ user|display_name }} </div>
          <div class="label-secondary">{{ user.username }}</div>
        </div>
      </div>
      <button id="user-modal-close" class="link" onclick="closeUserModal()">Close</button>
    </div>
    {% if user.is_staff %}
    <div class="user-modal-action">
      <a href="{% url 'admin:index' %}">Open admin interface</a>
    </div>
    <div class="user-modal-action">
      <a href="{% url 'photo_objects:configuration' %}">Show configuration status</a>
    </div>
    {% endif %}
    {% if perms.photo_objects.change_photo and perms.photo_objects.delete_photochangerequest %}
    <div class="user-modal-action">
      <a href="{% url 'photo_objects:next_photo_change_request' %}">Review photo change requests</a>
    </div>
    {% endif %}
    <form class="user-modal-action" method="POST" action="/users/logout?next={{ request.path }}">
      {% csrf_token %}
      <button id="user-modal-logout" class="link" type="submit">Logout</button>
    </form>
    <!-- Manual focus trap: move focus to first element in dialog. -->
    <div id="user-modal-post" tabindex="0" onfocus="focusElement('#user-modal-close')"></div>
  </div>
</dialog>
{% endif %}
<script>
  let previousFocus = null;

  function openUserModal() {
    document.querySelector('dialog.user-modal').showModal();

    previousFocus = document.activeElement;
    document.querySelector('#user-modal-close').focus();
  }

  function closeUserModal() {
    document.querySelector('dialog.user-modal').close();
  }

  function handleClose() {
    if (previousFocus) {
      previousFocus.focus();
      previousFocus = null;
    }
  }

  function handleClick(event) {
    if (event.target === event.currentTarget) {
      event.currentTarget.close()
    }
  }

  function focusElement(selector) {
    document.querySelector(selector).focus();
  }
</script>

photo_objects/django/templates/photo_objects/meta-og.html
{% if request.site and request.site.domain != "example.com" and photo and title %}
<meta property="og:title" content="{{ title }}" />
{% if description %}
<meta property="og:description" content="{{ description }}" />
{% endif %}
<meta property="og:image" content="https://{{ request.site.domain }}/img/{{ photo.album.key }}/{{ photo.filename }}/md" />
<meta property="og:type" content="website" />
<meta property="og:url" content="https://{{ request.site.domain }}{{ request.path }}" />
{% endif %}

photo_objects/django/templates/photo_objects/preview.html
<div class="preview">
  <div class="surface">
    <div class="image">
      {% if preview.photo %}
      <img src="/img/{{ preview.photo.album.key }}/{{ preview.photo.filename }}/sm" alt="{{ preview.photo.alt }}"
        style="background: url(data:image/png;base64,{{ preview.photo.tiny_base64 }}); background-size: 100% 100%; font-size: 0;"
        height="{{ preview.photo.thumbnail_height }}" width="{{ preview.photo.thumbnail_width }}" />
      {% else %}
      <div class="photo-placeholder"></div>
      {% endif %}
    </div>
    <div class="title-and-description labels">
      <span class="label-primary">{{ preview.title }}</span>
      <p class="label-secondary">{{ preview.description }}</p>
      <span class="host">{{ request.site.domain }}</span>
    </div>
  </div>
  {% if preview.helptext %}
  <span class="helptext">
    {{ preview.helptext }}
  </span>
  {% endif %}
</div>

photo_objects/django/templates/photo_objects/problem.html
{% extends 'photo_objects/base.html' %}

{% block header %}
{% include 'photo_objects/header.html' %}
{% endblock %}

{% block content %}
<dl class="problem">
  <dt>Title</dt>
  <dd>{{ problem_title }}</dd>
  <dt>Status</dt>
  <dd>{{ status }}</dd>
</dl>
{% endblock %}

photo_objects/django/templates/photo_objects/user-profile-content.html
{% load photo_objects_extras %}
{{ user|initials }}